In [58]:
import re
from pathlib import Path

import numpy as np
import pandas as pd
from tensorflow.keras.utils import to_categorical

path = Path.cwd() / 'one' / 'The Whisperer in Darkness.txt'
file = open(path, 'r', encoding='utf8').read()
data = re.findall(r'[a-z]+', file.lower())

x_seq = []
y_seq = []
vectors = pd.read_pickle('vectors.pkl')
for i in range(len(data) - 3):
    x = data[i:i + 3]  # make 3-grams
    y = data[i + 3]
    cur_x = [vectors[word] for word in x if word in vectors]
    if len(cur_x) == 3 and y in vectors:
        x_seq.append(cur_x)
        y_seq.append(vectors.index.get_loc(y))

x_seq = np.array(x_seq)
y_seq = to_categorical(y_seq, num_classes=vectors.shape[0])

In [64]:
import tensorflow as tf

lstm = tf.keras.layers.LSTM(1000, return_sequences=True,)
lstm(x_seq[:5])

<tf.Tensor: shape=(5, 3, 1000), dtype=float32, numpy=
array([[[ 0.00247378, -0.00384468,  0.0079461 , ...,  0.06095395,
         -0.00935177,  0.05809736],
        [ 0.02868745, -0.00348663,  0.01100862, ...,  0.07156584,
         -0.05013086,  0.06545781],
        [ 0.0008312 , -0.07617963,  0.00367172, ...,  0.05953234,
         -0.03150234,  0.0717433 ]],

       [[ 0.02211387,  0.00228705,  0.00697859, ...,  0.0253546 ,
         -0.04207788,  0.02684418],
        [-0.00979931, -0.07062699,  0.002795  , ...,  0.02655088,
         -0.02397072,  0.03845115],
        [ 0.01269208, -0.02562674,  0.0167398 , ...,  0.03531225,
         -0.03907047,  0.0683414 ]],

       [[-0.03184336, -0.06956246, -0.00434087, ...,  0.0175669 ,
          0.00859575,  0.01389177],
        [-0.00493624, -0.02132089,  0.00920817, ...,  0.0376015 ,
         -0.02124637,  0.05140587],
        [-0.04682901, -0.02464486, -0.03273578, ...,  0.04290241,
         -0.02939709,  0.0014386 ]],

       [[ 0.01484156, 

In [12]:
import pandas as pd
import spacy

import re

nlp = spacy.load('en_core_web_sm')
clean_vocab_list = [word for word in nlp.vocab.strings if re.fullmatch(r'[a-z]+', word)]

word_to_vector = pd.Series([], name='vector')
for word in clean_vocab_list:
    word_to_vector[word] = nlp(word).vector
word_to_vector.to_pickle('keyed_vectors.pkl')

c:\users\merkulov\documents\git\venv_openfl\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  if __name__ == '__main__':


In [11]:
vectors = pd.read_pickle('keyed_vectors.pkl')
vectors

a           [0.02819018, 0.009864252, -0.095220566, 0.5522...
aa          [-0.72708106, -0.3900509, -0.5274905, -0.24052...
aaa         [0.2759483, -0.84107316, -0.4709188, -0.121549...
aaaaahhh    [-0.39636, -0.52181447, -0.8544498, -0.0328585...
aab         [0.05131094, -0.5333605, -0.13755266, 0.309400...
Name: vector, dtype: object

In [28]:
tok2.vector

array([ 1.7234211 ,  0.70698   ,  0.07531004,  0.01016416,  0.90625674,
       -0.6563784 , -0.2947484 , -1.413888  , -0.5794049 , -0.2622171 ,
        0.8249276 , -0.4351025 , -0.32808983,  0.61241966, -0.19234025,
        0.32532322,  0.10879372,  0.06578569, -0.6768458 , -0.1377917 ,
       -0.8914129 , -0.6982869 ,  0.1900026 , -0.1436843 , -0.07635674,
        0.36350653,  0.6082434 , -0.21159156,  0.3636239 ,  0.0854439 ,
       -0.25609127,  0.1762818 , -0.28762445, -0.0117182 ,  0.2569304 ,
       -0.423652  , -0.4956298 ,  0.31628734,  1.0616965 ,  0.15893973,
       -0.15172145, -0.5052287 , -0.06382523,  0.6445457 ,  0.35854506,
        0.03501716, -0.1134971 ,  0.30475333, -0.3105463 ,  0.08665343,
        0.3017515 ,  0.00964418,  0.3062988 , -0.9406882 , -0.3071625 ,
        0.2866875 , -0.07427119, -0.2365871 ,  0.28920767, -0.6069183 ,
       -0.42465514, -0.01203269,  0.16526166, -1.2865363 , -0.48753422,
       -0.1325486 , -0.6748189 , -0.21193369, -0.53277934,  0.06